version: "3.5"
services:
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:latest
    ports:
      - 8428:8428
    volumes:
      - ./victoriametrics:/storage
    restart: "no"
  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.7
    depends_on:
      - "victoriametrics"
    ports:
      - 3100:3000
    volumes:
      - ./grafana:/var/lib/grafana
    restart: "no"
  dns-server:
    container_name: dns-server
    hostname: dns-server
    image: technitium/dns-server:latest
    network_mode: "host"
    environment:
      - DNS_SERVER_DOMAIN=dns-server #The primary domain name used by this DNS Server to identify itsel
      - DNS_SERVER_ADMIN_PASSWORD=password #DNS web console admin user password.
    volumes:
      - ./dns:/etc/dns
    ports:
      - 5380:5380
    restart: "no"
